import { useState, useCallback } from 'react';
import { xaiService, XAIResponse } from '../services/xaiService';
import toast from 'react-hot-toast';

export interface UseXAIReturn {
  // State
  isLoading: boolean;
  isConfigured: boolean;
  error: string | null;
  lastResponse: any | null;
  
  // Configuration
  configStatus: {
    configured: boolean;
    model: string;
    baseUrl: string;
  };
  
  // Actions
  sendMessage: (message: string, systemPrompt?: string) => Promise<string>;
  getAgentRecommendations: (systemMetrics: any) => Promise<string>;
  analyzeAgentPerformance: (agentData: any) => Promise<string>;
  generateStrategicInsights: (businessMetrics: any) => Promise<string>;
  
  // Utilities
  clearError: () => void;
}

export const useXAI = (): UseXAIReturn => {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lastResponse, setLastResponse] = useState<any | null>(null);

  const configStatus = xaiService.getConfigStatus();

  const handleError = useCallback((err: Error) => {
    setError(err.message);
    toast.error(`xAI API Error: ${err.message}`);
  }, []);

  const sendMessage = useCallback(async (
    message: string, 
    systemPrompt?: string
  ): Promise<string> => {
    if (!configStatus.configured) {
      const errorMsg = 'xAI API is not configured. Please set VITE_XAI_API_KEY in your environment variables.';
      setError(errorMsg);
      toast.error(errorMsg);
      throw new Error(errorMsg);
    }

    setIsLoading(true);
    setError(null);

    try {
      const response = await xaiService.sendMessage(message, systemPrompt);
      setLastResponse(response);
      toast.success('Message sent to Grok successfully');
      return response.content;
    } catch (err) {
      const error = err instanceof Error ? err : new Error('Unknown error');
      handleError(error);
      throw error;
    } finally {
      setIsLoading(false);
    }
  }, [configStatus.configured, handleError]);

  const getAgentRecommendations = useCallback(async (systemMetrics: any): Promise<string> => {
    if (!configStatus.configured) {
      const errorMsg = 'xAI API is not configured. Please set VITE_XAI_API_KEY in your environment variables.';
      setError(errorMsg);
      toast.error(errorMsg);
      throw new Error(errorMsg);
    }

    setIsLoading(true);
    setError(null);

    try {
      const response = await xaiService.getAgentRecommendations(systemMetrics);
      toast.success('Agent recommendations generated by Grok');
      return response;
    } catch (err) {
      const error = err instanceof Error ? err : new Error('Unknown error');
      handleError(error);
      throw error;
    } finally {
      setIsLoading(false);
    }
  }, [configStatus.configured, handleError]);

  const analyzeAgentPerformance = useCallback(async (agentData: any): Promise<string> => {
    if (!configStatus.configured) {
      const errorMsg = 'xAI API is not configured. Please set VITE_XAI_API_KEY in your environment variables.';
      setError(errorMsg);
      toast.error(errorMsg);
      throw new Error(errorMsg);
    }

    setIsLoading(true);
    setError(null);

    try {
      const response = await xaiService.analyzeAgentPerformance(agentData);
      toast.success('Agent performance analyzed by Grok');
      return response;
    } catch (err) {
      const error = err instanceof Error ? err : new Error('Unknown error');
      handleError(error);
      throw error;
    } finally {
      setIsLoading(false);
    }
  }, [configStatus.configured, handleError]);

  const generateStrategicInsights = useCallback(async (businessMetrics: any): Promise<string> => {
    if (!configStatus.configured) {
      const errorMsg = 'xAI API is not configured. Please set VITE_XAI_API_KEY in your environment variables.';
      setError(errorMsg);
      toast.error(errorMsg);
      throw new Error(errorMsg);
    }

    setIsLoading(true);
    setError(null);

    try {
      const response = await xaiService.generateStrategicInsights(businessMetrics);
      toast.success('Strategic insights generated by Grok');
      return response;
    } catch (err) {
      const error = err instanceof Error ? err : new Error('Unknown error');
      handleError(error);
      throw error;
    } finally {
      setIsLoading(false);
    }
  }, [configStatus.configured, handleError]);

  const clearError = useCallback(() => {
    setError(null);
  }, []);

  return {
    // State
    isLoading,
    isConfigured: configStatus.configured,
    error,
    lastResponse,
    
    // Configuration
    configStatus,
    
    // Actions
    sendMessage,
    getAgentRecommendations,
    analyzeAgentPerformance,
    generateStrategicInsights,
    
    // Utilities
    clearError,
  };
};
